type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Database Query"
      parameters:
        componentName: "Start"
    Database Query:
      type: "database-query"
      parameters:
        componentName: "Stage Cities"
        basicAdvancedMode: "Advanced"
        databaseType: "PostgreSQL"
        connectionUrl: "jdbc:postgresql://training.csti6ews2u0k.us-east-1.rds.amazonaws.com:5432/training_db"
        username: "postgres"
        password: "Postgres"
        connectionOptions:
        sqlQuery: |
          SELECT city, country_code, latitude, longitude, population
          FROM matilliontraining.city
          WHERE city IN ('Sao Paulo', 'London', 'Madrid', 'Denver', 'Paris', 'Beijing', 'Rio de Janeiro', 'Shanghai', 'Sydney', 'Manchester''New York');
        fetchSize:
        type: "Standard"
        primaryKeys:
        warehouse1: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "src_city"
        stage1: "[Custom]"
        stagePlatform: "Snowflake Managed"
        loadOptions:
        sshTunnel:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    Start:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    Database Query:
      position:
        x: 180
        "y": -80
      tempMetlId: 2
  notes:
    "1":
      position:
        x: 530
        "y": -170
      size:
        height: 420
        width: 300
      theme: "white"
      content: |-
        ### Database Query

        The **Database Query** component is used to execute a SQL query against a specified database. In this case, it is configured to connect to a PostgreSQL database using the provided connection URL, username, and password. The SQL query selects specific columns (`city`, `country_code`, `latitude`, `longitude`, `population`) from the `matilliontraining.city` table where the city is one of the listed cities. The results of this query are staged into a target table named `src_city` in Snowflake. This component is essential for extracting data from the source database and preparing it for further processing or transformation within the pipeline.
