type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Database Query"
      parameters:
        componentName: "Start"
    Database Query:
      type: "database-query"
      parameters:
        componentName: "Stage Cities"
        basicAdvancedMode: "Advanced"
        databaseType: "PostgreSQL"
        connectionUrl: "jdbc:postgresql://training.csti6ews2u0k.us-east-1.rds.amazonaws.com:5432/training_db"
        username: "postgres"
        password: "Postgres"
        connectionOptions:
        sqlQuery: |
          SELECT city, country_code, latitude, longitude, population
          FROM matilliontraining.city
          WHERE city IN ('Sao Paulo', 'London', 'Madrid', 'Denver', 'Paris', 'Beijing', 'Rio de Janeiro', 'Shanghai', 'Sydney', 'Manchester');
        fetchSize:
        type: "Standard"
        primaryKeys:
        warehouse1: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "src_city"
        stage1: "[Custom]"
        stagePlatform: "Snowflake Managed"
        loadOptions:
        sshTunnel:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    Start:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    Database Query:
      position:
        x: 160
        "y": 0
      tempMetlId: 2
